### ISSUE TITLE
toolbar-vue 会不会有vue2.x 版本

### ISSUE THREAD

**Issue by QJBChou** [yanmao-cc/am-editor#33]
项目中需要文档编辑器，所以想用 am-editor 实现，但是项目的vue2 的 ，am-editor 的 toolbar-vue 是vue3 ....

**Comment by yanmao-cc** [comment]
主要我本身对react熟悉些，然后因为需要用到vue，我直接使用的vue3，对vue2还没使用过，所以做vue2版本可能需要一些时间，短时间内无法支持。

但是本质上 toolbar 就是一堆button、dropdown外加颜色选择器。然后其 onClick 事件调用 engine.command 执行插件命令或调用状态。所以直接改写vue3语法到vue2上也是可行的。

**Comment by yanmao-cc** [comment]
还有一种简单的方式就是使用vue3做编辑器，然后嵌套一个iframe

**Comment by QJBChou** [comment]
明白了，谢谢，我去试试嵌套一个iframe，我有时间用vue2重写个toolbar，等我看完vue3🙄
