### ISSUE TITLE
vue 版本的 toobar 组件降级到Vue2中，指令无法正确得到传递

### ISSUE THREAD

**Issue by elton-zhou** [yanmao-cc/am-editor#37]
如题

**Comment by yanmao-cc** [comment]
有复现吗？

**Comment by elton-zhou** [comment]
> 有复现吗？

就是将现有的toolbar-vue组件采用@vue/composition-api替换Vue

**改动点**

`toolbar-vue/plugin/components/collapse.js`

![image](https://user-images.githubusercontent.com/80742139/130588997-98f82d34-78f0-4016-b489-f49663a7066e.png)

部分tool组件使用正常，大部分都失效了；`Ctrl + / `  快速插入的同样方法失效了

尝试在 `components/table.vue` 修复插入表格，的确成功了

```javascript
triggerSelect(event, rows, cols) {
    if (this.onSelect) { this.onSelect(event, rows + 1, cols + 1) } 
    else if (this.$vnode.data?.onSelect) {
      this.$vnode.data.onSelect(event, rows + 1, cols + 1)
    }
}
```

看样子编辑区域基本正常，但toolbar部分与 `@aomao/*` 插件类引用关系不明，是否考虑这些插件组件提供统一方法暴露自生配置、指令、方法等？toolbar 只需通过编辑器实例获取这些即可？

**Comment by yanmao-cc** [comment]
toolbar 除了 `ctrl + /` 快速插入外，其它都是使用 `engine.command.excute(插件名称，参数)` 去调用插件命令的。`toolbar` 与 engine 几乎没有绑定，都是通过编辑器实例去调用插件命令。当然，快速插入只是toolbar本身扩展的插件。

大部分情况下指令无法传递可能是props更新后、子组件没有得到更新，得调试看看

**Comment by elton-zhou** [comment]
> toolbar 除了 `ctrl + /` 快速插入外，其它都是使用 `engine.command.excute(插件名称，参数)` 去调用插件命令的。`toolbar` 与 engine 几乎没有绑定，都是通过编辑器实例去调用插件命令。当然，快速插入只是toolbar本身扩展的插件。
> 
> 大部分情况下指令无法传递可能是props更新后、子组件没有得到更新，得调试看看

应该是 `engine.command.excute(插件名称，参数)` 中的参数传递失败了，可否考虑将 **参数** 从 `getToolbarDefaultConfig` 方法中获得，并将其移入 `engine` 中，这样似乎更合理

**Comment by elton-zhou** [comment]
sorry，说的太多了😅

**Comment by yanmao-cc** [comment]
这里的参数是插件的参数，大部分插件没有强制性参数，这里也可以根据不同需求配置不同的参数。
```ts
items:[
  [{name:'bold', command:['参数1','参数2']}]
]
```

你能告诉我哪些插件有问题吗？主要有 button、dorpdown、color、collapse 四种类型的组件，如果一个插件执行有问题，应该这个类型的组件都有问题，大概率是props变更后没有传递到子组件吧

**Comment by yanmao-cc** [comment]
https://cn.vuejs.org/v2/api/index.html#vm-mount

快捷键我看 vue2.x 中 mount 方法是，实例化一个组件？
```javascript
var MyComponent = Vue.extend({
  template: '<div>Hello!</div>'
})

// 创建并挂载到 #app (会替换 #app)
new MyComponent().$mount('#app')

// 同上
new MyComponent({ el: '#app' })

// 或者，在文档之外渲染并且随后挂载
var component = new MyComponent().$mount()
document.getElementById('app').appendChild(component.$el)
```
vue3.x 中的方法是实例化 Vue 实例
```javascript
const RootComponent = { 
  /* 选项 */ 
}
const app = Vue.createApp(RootComponent)
const vm = app.mount('#app')
```

**Comment by elton-zhou** [comment]
> https://github.com/zb201307/am-editor-vue2

好，谢谢！
