### ISSUE TITLE
是不是只能用ts？

### ISSUE THREAD

**Issue by miss7cd** [yanmao-cc/am-editor#38]
**Describe the bug**
![image](https://user-images.githubusercontent.com/38612985/130594737-9450774f-421f-4c9a-9293-68885c50b76a.png)

**To Reproduce**
vue3.0项目，按vue案例中的写法，改成js后，控制台有警告，toolBar无法渲染

**Comment by yanmao-cc** [comment]
不会的，ts编译后也是js的，会不会vue版本有关系，现在 vue版本是 3.2.4

**Comment by miss7cd** [comment]
确实是vue版本问题，3.1.x升级到3.2.x。没有再出现问题，非常感谢
