### ISSUE TITLE
插件toolbar的react版本和我项目本身版本不一样

### ISSUE THREAD

**Issue by listar** [yanmao-cc/am-editor#45]
如题：
插件toolbar的react版本和我项目本身版本不一样，造成项目没法直接使用toolbar插件，应该怎么处理？

**Comment by yanmao-cc** [comment]
升级react版本能行吗？

**Comment by listar** [comment]
> 升级react版本能行吗？

就是想保持老版本，怕有其他影响
"react": "^17.0.1",
        "react-dom": "^17.0.1",
降级到16.3再对toolbar插件源码打包这个方案可以不

**Comment by yanmao-cc** [comment]
那antd版本也得降

**Comment by listar** [comment]
好的 ，谢谢大佬！ 我试试
