### ISSUE TITLE
希望markdown 兼容更多一点语法

### ISSUE THREAD

**Issue by yue1123** [yanmao-cc/am-editor#46]
目前使用最舒服的只有标题语法,其他的,其他的大部分语法都不生效

**Comment by yanmao-cc** [comment]
你可能忘记按空格了， **aa** + 空格 才会转换

**Comment by yue1123** [comment]
抱歉，是我没用对，我用字体加粗和链接语法都没按空格，以为不支持



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: yanmao ***@***.***&gt;
发送时间: 2021年9月25日 15:58
收件人: yanmao-cc/am-editor ***@***.***&gt;
抄送: 花开半亩地 ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[yanmao-cc/am-editor] 希望markdown 兼容更多一点语法 (#46)





 
你可能忘记按空格了， aa + 空格 才会转换
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
