### ISSUE TITLE
这个确定可以用吗？？？

### ISSUE THREAD

**Issue by balck-paint** [yanmao-cc/am-editor#50]
作者您好，您确定这个真的可以用吗？真心发问，没别的意思。知道开源不易，但是这个我跑了一下实在是不能用啊
不知道你测试过没有
首先这个粘贴外部md文档或者是转化后的html，甚至是word复制过来的纯文档，格式都会错乱。搞得我都无语了
    <img src="http://r1hodihcg.hn-bkt.clouddn.com/FiEy1udnENtxfsSmlNAQ_meseW2n" alt="">
然后就是这个复制慢，改格式慢，一篇一两万字的纯文档，加个粗或者改个字体都肉眼可见的卡
实在是没办法用，实在不懂是我没配置好还是编辑器本身的问题。

**Comment by balck-paint** [comment]
[上传了个视频链接您看看](http://r1hodihcg.hn-bkt.clouddn.com/%E6%A0%BC%E5%BC%8F%E5%B7%A5%E5%8E%82%20%E5%B1%8F%E5%B9%95%E5%BD%95%E5%83%8F20211107_190912.mp4)

**Comment by balck-paint** [comment]
我在官网那个在线编辑器上试了一下，并不卡，这就奇怪了```````我等会把实例项目拉下来跑着试试

**Comment by yanmao-cc** [comment]
复制再粘贴板里面有 html 和 text 两种类型，如果提示到检测到 markdown 那个可能是检测到 text 里面的文本有符合markdown 的语法，但是又不全部是。所以你选择转换其实就是把 text 里面的值粘贴进去了。

卡这个，看起来像是哪里死循环了，大概率是bug或者哪里使用造成了这种bug。另外如果 字体大小、字体 对文档来说不重要的发，可以把这两个插件再粘贴的时候排除也会有助于提高粘贴的速度，因为一般不管是word还是其它文档复制的时候总是带着一些微软雅黑或者其它的字体设置。
```ts
// 粘贴的时候过滤一些样式插件
    engine.on('paste:schema', schema => {
		const plugins = ['fontsize', 'fontfamily']
		plugins.forEach(pluginName => {
			const plugin = engine.plugin.components[pluginName]
			if(!plugin || plugin.kind !== 'mark') return
			const pluginSchema = (plugin as MarkPlugin).schema()
			const schemas: SchemaMark[] = []
			if(Array.isArray(pluginSchema)) {
				pluginSchema.forEach(schema => schemas.push(schema))
			} else {
				schemas.push(pluginSchema)
			}
			schemas.forEach(rule => {
				schema.remove(rule)
			})
		})
    })
```

**Comment by balck-paint** [comment]
@yanmao-cc 我重启了电脑，另外重新把官网的示例拉下下跑了一下，好多了。之前可能是卡住了，然后我一直重试，然后越来越卡。
另外我测试了和其他的编辑器，确实相对比较卡，还是有优化空间的。
还有个问题，在你们的示例布局下我复制别的md文档，然后页面直接被撑到最大，顶部的菜单栏也看不见了，这个不清楚是怎么回事，是你们有检测如果空间不够自动全屏吗?
然后我自己改了布局样式，目前来说没有出现这个问题

**Comment by yanmao-cc** [comment]
示例里面除了 react 是直接使用当前package里面的包执行的外，vue使用的仍然是上一个版本的文件。2.6 版本是做了一些机制改动，这两天累计了一些bug修复了再commit日志里，预计明天才会再发一个版本

**Comment by balck-paint** [comment]
@yanmao-cc  看了下文档中的给出的接口，发现可扩展性真的很高，很强大，但是由于没有示例，所以在用法上还是有些疑惑

比如我现在有个需求，自定义一个toolbar,点击后在编辑器中插入相应的元素，比如说图片、表单、甚至更复杂的元素，然后这个是怎么做的呢？
文档中应该是推荐使用card或者block，我试图去创建它，但是都失败了，然后我只能退而其次，使用以下方式插入自定义内容
<img src="http://r1hodihcg.hn-bkt.clouddn.com/Snipaste_2021-11-08_09-45-03.png">

然后还有那个插件命令，不能在外部使用吗？只能在点击toolbar后触发吗？

可能是我文档阅读能力比较差，但是由于这个编辑器是一个比较新的开源项目，网上并没有相关的用法，所以只能来麻烦作者了，如果您有时间可以回答一下，期待您的回复

**Comment by yanmao-cc** [comment]
使用引擎实例去调用插件的命令 `engine.command.execute('插件名称')`，toolbar 上的按钮单击也是这里调用这个命令

**Comment by balck-paint** [comment]
@yanmao-cc  
可以了，之前的命令第一次用不知道是那里没配好。刚才可以了，功能还是很强大的。真香
另外刚刚看到了插件开发，隐藏的比较深，得仔细研究一下，功能更强大。card插件好像是渲染一些比较复杂可以结合vue等使用外部ui库的，但是如果只是单纯的插入一些文本段落用什么方式呢
另外不知道有没有群，有不懂的可以问问群友

**Comment by yanmao-cc** [comment]
可以试试这样
const fragment = doc.createDocumentFragment();
fragment.appendChild(...);
engine.change.insert(fragment)

一般情况下都是由插件去执行插入，因为插件有schema约束，不会造成未定义的节点出现在文档中

在Readme 里面有群号
