### ISSUE TITLE
官网示例中粘贴Markdown内容转化为富文本内容是否如何实现的？

### ISSUE THREAD

**Issue by luojinghui** [yanmao-cc/am-editor#54]
官网首页：https://editor.yanmao.cc/ 示例程序中，复制一段Markdown内容，是如何检测并转换为富文本内容展示的？

**Comment by yanmao-cc** [comment]
正则匹配提取符合markdown语法的文本，然后转换成 DOM 节点

**Comment by luojinghui** [comment]
> 正则匹配提取符合markdown语法的文本，然后转换成 DOM 节点

MD的语法挺多的，有类似的Demo可以参考吗？

**Comment by yanmao-cc** [comment]
这里是按照每个插件配置的markdown语法去转换的

**Comment by luojinghui** [comment]
好的，我研究下，多谢
