### ISSUE TITLE
希望可以支持nuxt.js

### ISSUE THREAD

**Issue by zhpgit** [yanmao-cc/am-editor#59]
大多数主流富文本编辑器都可以支持，这个在nuxt.js里面引入，报Cannot find module 'xxx'错误，engine文件通过vue实例化引入后，可以展示编辑器，但是例如Bold扩展还是报以上错误，这个编辑器很不错，希望早日可以实现。🤔

**Comment by yanmao-cc** [comment]
https://github.com/yanmao-cc/am-editor-nuxt
