### ISSUE TITLE
上传图片，可不可以携带 cookie

### ISSUE THREAD

**Issue by hedeqiang** [yanmao-cc/am-editor#60]
https://editor.yanmao.cc/zh-CN/plugin/plugin-image
插件，是否可以设置允许携带 cookie ，因一些因素，需要授权 cookie 才可以上传。可否设置类似：credientials 这样的参数

**Comment by yanmao-cc** [comment]
headers: {cookie: 'xxxxx' }

**Comment by hedeqiang** [comment]
@yanmao-cc  这个不允许设置cookie 
Refused to set unsafe header "cookie"

**Comment by yanmao-cc** [comment]
https://www.w3.org/TR/XMLHttpRequest/#the-setrequestheader%28%29-method
都试试看
https://indomi.github.io/2019/03/05/%E8%B7%A8%E5%9F%9Fcookie%E6%90%BA%E5%B8%A6%E5%AE%9E%E8%B7%B5/

```ts
"Cookie": document.cookie
```

**Comment by hedeqiang** [comment]
貌似不行

**Comment by yanmao-cc** [comment]
> 貌似不行

是跨域cookie吧？跨域可以设置一些类似 Authoritarian 这样的请求头会好一点，要么就做个反向代理

**Comment by hedeqiang** [comment]
不是，我们的上传服务器需要进行登陆，而登陆依赖于cookie，所以就不行，之前使用 element 上传，他提供了 `with-credentials` 参数，设置允许发送 cookie，所以没有问题

**Comment by yanmao-cc** [comment]
看代码这个选项没有开放出来，下一个版本解决吧

**Comment by hedeqiang** [comment]
OK，预计下个版本的时间点是什么时候
