### ISSUE TITLE
此富文本支持插入html标签吗？

### ISSUE THREAD

**Issue by lloveyoutjq** [yanmao-cc/am-editor#66]
此富文本支持插入html标签吗？ 就像Typora一样

**Comment by yanmao-cc** [comment]
什么样的格式呢？基本上都是可以的。是插件形式？还是只是放在一个区域不可编辑？

**Comment by lloveyoutjq** [comment]
> 什么样的格式呢？基本上都是可以的。是插件形式？还是只是放在一个区域不可编辑？

![image](https://user-images.githubusercontent.com/38431925/148679953-c2b4ad12-4ac6-463f-8909-ebe4665767c8.png)
![image](https://user-images.githubusercontent.com/38431925/148679968-884fa710-b91d-4010-84e8-a974ab804427.png)
就是这种的，而你这个组件 好像不支持 输入 html 标签，因为有些文章 用户可能要自定义一些样式的

**Comment by yanmao-cc** [comment]
这个输入然后自动转换确实没有。这个逻辑应该跟markdown转换差不多，但是其实有样式这类的需求，就应该做个插件吧，就像加粗、斜体这样的插件，通过快捷键和工具栏去增加样式
