### ISSUE TITLE
插件plugin-image升级到最新版本是不支持预览模式图片放大了吗？

### ISSUE THREAD

**Issue by pyunfei** [yanmao-cc/am-editor#67]
"@aomao/plugin-image": "^2.7.3"
![image](https://user-images.githubusercontent.com/42907484/147798780-e20fa1f5-f46f-4768-8913-d825f013c2ab.png)

**Comment by yanmao-cc** [comment]
engine 升级了么？

**Comment by pyunfei** [comment]
> 发动机升级了么？

全都是升级到了3.7.3 
我看到今天凌晨又升级了到3.7.5  是不是要在升级一下

**Comment by pyunfei** [comment]
> engine 升级了么？

好了 解决了 现在升级到3.7.5  就可以解决这个问题
