### ISSUE TITLE
升级新版本后报错  ‘@aomao/engine' does not contain an export named 'ActiveTrigger

### ISSUE THREAD

**Issue by H-Sven** [yanmao-cc/am-editor#68]
![image](https://user-images.githubusercontent.com/26042365/148207895-2850ff15-971a-4d0e-9eab-48c29b13d5d6.png)

![image](https://user-images.githubusercontent.com/26042365/148207949-764d96b7-82fc-40cf-afb0-d934822008b2.png)

以前的版本是用这个ActiveTrigger的， 是从哪个版本开始移除了这个声明吗？

**Comment by yanmao-cc** [comment]
使用 CardActiveTrigger

**Comment by H-Sven** [comment]
> 使用 CardActiveTrigger


这是哪个版本的改动， 而且这是node_modules中的代码， 并不是我自己写的，如何处理

**Comment by H-Sven** [comment]
报错文件是node_modules/@aomao/plugin-status/src/components/index.ts

**Comment by yanmao-cc** [comment]
如果你升级了引擎库，应该把所有插件都升级了。你可以看一下node_modules 里面 @aomao/engine 中的版本号

**Comment by H-Sven** [comment]
> 如果你升级了引擎库，应该把所有插件都升级了。你可以看一下node_modules 里面 @aomao/engine 中的版本号

版本号是@aomao/engine@2.6.5， 我并不是直接升级了@aomao/engine， 是我的项目中使用了一个第三方npm包， 这个包中依赖的是^2.4.6， 在我npm install 主项目时，出现了上述问题，我需要联系第三方包作者升级 @aomao/engine 吗？ 
另外我项目中的package-lock.json出现了变动，会是这个导致版本号被锁定吗

**Comment by yanmao-cc** [comment]
第三方包是依赖的2.4的，为啥你这把是2.6的呢？应该是你这边指定了新的版本号？

**Comment by H-Sven** [comment]
> 第三方包是依赖的2.4的，为啥你这把是2.6的呢？应该是你这边指定了新的版本号？

问题已解决， 本地的package-lock.json导致部分依赖的版本不对，删除本地package-lock.json重新install就好了
