### ISSUE TITLE
链接插件，无法使用

### ISSUE THREAD

**Issue by zhaodeezhu** [yanmao-cc/am-editor#70]
![image](https://user-images.githubusercontent.com/58294623/148920802-cf475c43-5f38-4e2e-aa66-5ac4e7748383.png)
可以直接去官网复现

**Comment by zhaodeezhu** [comment]
为什么关闭了？已经修复，还是？

**Comment by zhaodeezhu** [comment]
什么时候可以发个版本呢

**Comment by yanmao-cc** [comment]
发了
