### ISSUE TITLE
设置表格底色 色卡被表格表头遮挡

### ISSUE THREAD

**Issue by ly01112020** [yanmao-cc/am-editor#77]
Window 10 Edge 97.0
问题如图所示

![249DF482-B5DB-476e-BEDB-A26AB53BDEE9](https://user-images.githubusercontent.com/4043937/150288586-c92a9b81-d47c-4f55-871b-a160f7ce36db.png)

**Comment by ly01112020** [comment]
另外最大化后如何退出？，无菜单，esc ,control + z 均无法退
![Dingtalk_20220120145600](https://user-images.githubusercontent.com/4043937/150289024-02312d39-adc6-4094-93c7-3c3fa82726a3.jpg)
回

**Comment by yanmao-cc** [comment]
> 另外最大化后如何退出？，无菜单，esc ,control + z 均无法退 ![Dingtalk_20220120145600](https://user-images.githubusercontent.com/4043937/150289024-02312d39-adc6-4094-93c7-3c3fa82726a3.jpg) 回

上面的样式遮挡了，是有个返回按钮的，不过需要根据自身的页面情况调整 top 之类的
![image](https://user-images.githubusercontent.com/55792257/150289881-f68a791e-1e7b-4120-bc88-3260875f9010.png)

**Comment by yanmao-cc** [comment]
https://github.com/yanmao-cc/am-editor/releases/tag/%40aomao%2Fengine%402.7.18
