### ISSUE TITLE
请问@aomao/plugin-image如何设置图片100%宽度适应移动端屏幕？

### ISSUE THREAD

**Issue by ChuangShiOS** [yanmao-cc/am-editor#81]
![image](https://user-images.githubusercontent.com/65151203/150793690-2c3526bb-6e88-4c00-90ea-dbbb2e523efc.png)

**Comment by yanmao-cc** [comment]
图片宽度小于屏幕宽度就没办法了，强行把图片宽度拉到屏幕宽度就模糊了

**Comment by ChuangShiOS** [comment]
图片宽度大于屏幕宽度的情况呢？ 适配移动端屏幕宽度是很常见的需求了

**Comment by yanmao-cc** [comment]
大于的情况默认就是占满了的

**Comment by yanmao-cc** [comment]
> 大于的情况默认就是占满了的

如果pc端拉到了固定宽度就是那个宽度，得以这个宽度为准了

**Comment by ChuangShiOS** [comment]
移动端详情页面会经常放置多个图片，可能每个图片的宽度不一致，现在如果有一个设置宽度为100%，就可以解决屏幕适配的问题了

**Comment by yanmao-cc** [comment]
如果遇到宽度小于屏幕的，这张图片就会模糊掉，所以这个解决方案是个假象

**Comment by ChuangShiOS** [comment]
有时候图片宽度就相差几个px，就想有一个操作快速的让宽度对齐
![image](https://user-images.githubusercontent.com/65151203/150900123-800362b8-cc1a-468b-8460-4b8574b7a73a.png)

**Comment by ChuangShiOS** [comment]
![image](https://user-images.githubusercontent.com/65151203/150900459-b98139d1-afb5-411d-836d-1a48d8cd9830.png)

**Comment by yanmao-cc** [comment]
那就只能加个禁止拖动的选项了

**Comment by yanmao-cc** [comment]
```ts
image: {
  enableResizer: false,
  defaultType: 'block'
}

给图片插件配置一下这个就可以满足100%了
